#######################
# Docker Compose file #
#######################

version: '2.0'

services:     
    nlp_batch:
        build: ./images/nlp_batch
        volumes:
         - ./images/tomcat/war/CmisWebBrowser/processed:/home/nlp_batch/doc_processed/       
        restart:
            unless-stopped
        tty: true
        depends_on:
          - tomcat
    alfresco:
        environment:
          CONTENT_STORE: /mnt/content_store
          DB_KIND: mysql
          DB_PASSWORD: secret
          DB_HOST: mysql_db
        image: rsippl/alfresco
        ports:
          - "8080:8080"
        volumes:
          - ./images/alfresco/data:/mnt/content_store
          - ./images/alfresco/tomcat_log:/alfresco/tomcat/logs
        depends_on:
          - mysql_db
    mysql_db:
        image: mysql
        restart: always
        volumes:
          - ./images/db_data:/var/lib/mysql
        ports:
          - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: alfresco
          MYSQL_USER: alfresco
          MYSQL_PASSWORD: secret
    tomcat:
        image: bitnami/tomcat:8.0
        ports:
            - 8081:8081
        restart:
            unless-stopped
        tty: true
        environment:
          TOMCAT_HTTP_PORT_NUMBER: 8081
        volumes:
          - ./images/tomcat/war/:/bitnami/tomcat/data/
          - ./images/tomcat/logs:/opt/bitnami/tomcat/logs
    virtuoso:
        image: openlink/virtuoso_opensource:latest
        ports:
          - "1111:1111"
          - "8890:8890"
        volumes: 
          - ./images/virtuoso/database:/opt/virtuoso-opensource/database